algoritmo "matemática"
var
   N1, N2, Resultado: real

inicio
      Escreva ("Digite um numero: ")
      Leia (N1)
      Escreva ("Digite outro numero: ")
      Leia (N2)
      Escreval ("Você digitou:", N1, " e",N2)
      Resultado <- N1 + N2
      Escreval ("A soma entre:", N1, " e", N2, " é igual a:", Resultado)
      Resultado <- N1 - N2
      Escreval ("A subtração entre:", N1, " e", N2, " é igual a:", Resultado)
      Resultado <- N1 * N2
      Escreval ("A multiplicação entre:", N1, " e", N2, " é igual a:", Resultado)
      Resultado <- N1 / N2
      Escreval ("A divisão entre:", N1, " e", N2, " é igual a:", Resultado)
      Resultado <- Int(RaizQ(N1))
      Escreval ("A Raiz quadrada de :", N1, " é igual a:", Resultado)
      Escreval ("A Raiz quadrada de :", N2, " é igual a:", Resultado)

fimalgoritmo
